### PR TITLE
Multi arch docker

### PR DESCRIPTION
**Pull request by Gibby**
This will build and publish docker images to hub.docker.com for arm32 and x64.

* 1 every time there is a push to master branch for mguinness/intellicentergateway:arm32 and mguinness/intellicentergateway:x64
* 1 for each release to mguinness/intellicentergateway:arm32-VERSION and mguinness/intellicentergateway:x64-VERSION

### CODE REVIEW

**Comment by mguinness** [comment]
Thanks for PR I'll take a look at this at the w/end.  I'll probably merge the release & latest into one file only triggered on publish.

**Comment by mguinness** [comment]
It seems this isn't the way to build multi-arch Docker images, see [Multi-arch build and images, the simple way](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) for details.

**Comment by Gibby** [comment]
You can do that too, but it requires the upstream images to be able to be addressed via the variables. The dotnetcore upstream images are not named in an easy way to accomplish that.

**Comment by mguinness** [comment]
Can you go into more detail?  I thought that the .NET Core docker images have multi-arch manifests.

**Pull request closed without merging**
